name: lizzwe
description: A lightweight, intuitive, zero-overhead state manager for Flutter
version: 0.0.1
homepage: https://github.com/yourusername/lizzwe

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  # This section is for Flutter specific configuration
  # We'll add assets and fonts here if needed later 